CREATE TYPE "DealStage_next" AS ENUM (
  'NEW_INQUIRY',
  'CONTACTED',
  'REPLIED',
  'RFQ_RECEIVED',
  'QUOTED',
  'SAMPLE',
  'NEGOTIATING',
  'PROFORMA_INVOICE',
  'WON',
  'LOST',
  'UNQUALIFIED'
);

ALTER TABLE "deal" ALTER COLUMN "stage" DROP DEFAULT;

ALTER TABLE "deal"
ALTER COLUMN "stage" TYPE "DealStage_next"
USING (
  CASE "stage"::text
    WHEN 'DEMO_BOOKED' THEN 'NEW_INQUIRY'
    WHEN 'QUALIFIED_TO_BUY' THEN 'RFQ_RECEIVED'
    WHEN 'DECISION_MAKER_BOUGHT_IN' THEN 'NEGOTIATING'
    WHEN 'CONTRACT_SENT' THEN 'PROFORMA_INVOICE'
    WHEN 'CLOSED_WON' THEN 'WON'
    WHEN 'CLOSED_LOST' THEN 'LOST'
    WHEN 'UNQUALIFIED_TO_BUY' THEN 'UNQUALIFIED'
    ELSE "stage"::text
  END
)::"DealStage_next";

DROP TYPE "DealStage";
ALTER TYPE "DealStage_next" RENAME TO "DealStage";

ALTER TABLE "deal" ALTER COLUMN "stage" SET DEFAULT 'NEW_INQUIRY';
